In [2]:
from sklearn.datasets import load_iris
from sklearn.metrics import zero_one_loss
iris = load_iris()
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris['data'],
                                                    iris['target'],random_state=211)




In [3]:
X_train.shape
X_train[:,0]#this is the first column with data for sepal length

array([6.9, 4.9, 5.1, 5.8, 5.7, 5. , 4.8, 6.1, 5.1, 5.6, 4.3, 5.2, 5.6,
       6.4, 6.6, 4.8, 6.8, 5.6, 6.1, 5.4, 5.7, 4.5, 6.5, 5.9, 5.3, 6.7,
       4.8, 6.9, 6.1, 7.2, 6.4, 5. , 7.2, 6.3, 6. , 7.2, 5.4, 5.2, 6.7,
       4.8, 4.8, 6.3, 6.8, 7.7, 7.6, 5.1, 5. , 5.9, 5.5, 5.5, 4.6, 6.5,
       5.1, 5.5, 6.2, 7.9, 4.9, 5. , 6.3, 6. , 6.9, 6.1, 4.9, 5.1, 5. ,
       5.1, 5.5, 5.7, 6.5, 5.1, 5.6, 5. , 6.4, 6.7, 5.7, 5.5, 6.4, 6.3,
       6.5, 5.2, 5.7, 5.5, 5.1, 6.5, 6.2, 5.7, 6.3, 6. , 5. , 6.3, 6.3,
       6.8, 4.6, 5.7, 5.8, 6.2, 5.8, 5.1, 6.7, 5.8, 4.7, 4.7, 4.6, 6. ,
       5.8, 5.4, 4.4, 5. , 5.6, 7.1, 5.9, 4.6])

In [4]:
X_test.shape

(38, 4)

In [5]:
from sklearn.neighbors import KNeighborsClassifier
#CREATE THE OBJECT VIA THE CLASS
knn = KNeighborsClassifier(n_neighbors=5)

In [6]:
knn.fit(X_train,y_train)
#fit the model on the training set  

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [7]:
import numpy as np
X_new = np.array([[5,2.9,1,0.2]])
X_new.shape

(1, 4)

In [8]:
prediction = knn.predict(X_new)
#we call the predict method from the knn object 
print(prediction)

[0]


In [9]:
print(iris['target_names'][prediction])


['setosa']


In [10]:
y_pred = knn.predict(X_test)
#np.shape(y_pred)
y_test.shape
np.mean(y_test==y_pred)
#so the way it calculates this is corect guesses/total number of labels (38)
#you can print the shape of either y_test or y_pred
#y_test is only used as a comparisson to test it against our real predictions!!!
#y_test is only used as a comparison with y_pred, which is the real predicted array
#y_pred = knn.predict(X_test)

#np.mean(y_test==y_pred) first checks if
#all the values in y_test is equal to corresponding
#values in y_pred which either results in 0 or 1. 
#And then takes the mean of it (which is still 0 or 1).
#however, in our case it does not return 0 or 1...

#accuracy_score(y_test, y_pred) counts all the indexes where an element 
#of y_test equals to an element of y_pred and then
#divide it with the total number of elements in the list.

1.0

In [11]:
y_test.shape
#it is strane here that we dont use knn.score(y_pred,y_test) this
#but we use x_test. I cant reshape it but it doesnt matter
knn.score(X_test,y_test)

1.0

In [15]:
#This is question 2
y_pred = knn.predict(X_test)
#returns the percentage of missclassification
#
error_rate = zero_one_loss(y_test, y_pred)
error_rate
#y_pred

0.0

In [13]:
y_test

array([1, 2, 0, 0, 1, 0, 1, 1, 2, 2, 0, 0, 2, 2, 1, 2, 1, 1, 2, 2, 1, 1,
       1, 0, 1, 2, 1, 1, 0, 1, 0, 1, 2, 1, 2, 1, 2, 0])

In [98]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [99]:
X=np.genfromtxt('iris_data.txt')

In [100]:
X[:3,]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [101]:
y_pred==y_test

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False])

In [102]:
(y_pred==y_test)+1 

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1])

In [103]:
y_pred==y_test+1

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True])

In [104]:
(y_pred==y_test)[0]+1


2

In [105]:
np.mean(y_pred==y_test)

0.9736842105263158